runtime: python
env: flex
api_version: 1
threadsafe: yes
entrypoint: gunicorn --limit-request-line 9994 --timeout 120 --graceful-timeout 120 --keep-alive 5000 -b :$PORT cloud_SRI_python.wsgi

runtime_config:
  python_version: 3

handlers:
  - url: /static
    static_dir: static
  - url: .*
    script: app.wsgi.application

manual_scaling:
  instances: 1
resources:
  cpu: 8
  memory_gb: 32
  disk_size_gb: 16

builtins:
  - django_wsgi: on